# Generated by Django 4.0.4 on 2022-10-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='donationCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('describe_email', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('P_o_box_no', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mainObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('describe_Phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parttener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(unique=True)),
                ('Date_joined', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sendUsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('massege', models.TextField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(blank=True, max_length=200, null=True)),
                ('tittle', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('faceBook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team')),
                ('Date_joined', models.DateField()),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
                ('description', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.servicecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects')),
                ('description', models.TextField()),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('finished', 'finished'), ('progress', 'progress')], max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('laste_update', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.category')),
            ],
        ),
    ]
