# Generated by Django 3.2 on 2023-03-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_auto_20230327_0011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donationCaption',
            new_name='contactDescription',
        ),
    ]
