# Generated by Django 3.2 on 2023-05-31 20:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0004_rename_donationcaption_contactdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
