# Generated by Django 3.2 on 2023-06-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0006_auto_20230601_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='motor',
            new_name='motto',
        ),
    ]
