# Generated by Django 3.2 on 2023-06-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0007_rename_motor_motto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name_plural': '14. Background'},
        ),
        migrations.AlterModelOptions(
            name='banners',
            options={'verbose_name_plural': '20. Banners'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '18. Categories'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': '04. Companies'},
        ),
        migrations.AlterModelOptions(
            name='contactdescription',
            options={'verbose_name_plural': '05. Contact Description'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': '02. Emails'},
        ),
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name_plural': '13. Goal'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '03. Location'},
        ),
        migrations.AlterModelOptions(
            name='mainobjective',
            options={'verbose_name_plural': '09. main objectives'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name_plural': '11. mission'},
        ),
        migrations.AlterModelOptions(
            name='motto',
            options={'verbose_name_plural': '12. Motto'},
        ),
        migrations.AlterModelOptions(
            name='officephone',
            options={'verbose_name_plural': '01. Office Phone'},
        ),
        migrations.AlterModelOptions(
            name='parttener',
            options={'verbose_name_plural': '06. Patterners'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '17. Project'},
        ),
        migrations.AlterModelOptions(
            name='sendusmessage',
            options={'verbose_name_plural': '19. sent Messages'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': '15. Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': '16. service Categories'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': '07. staff'},
        ),
        migrations.AlterModelOptions(
            name='staffcaption',
            options={'verbose_name_plural': '08. staff Caption'},
        ),
        migrations.AlterModelOptions(
            name='vission',
            options={'verbose_name_plural': '10. vission'},
        ),
    ]
