# Generated by Django 3.2 on 2023-06-02 21:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0008_auto_20230603_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='Note',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
