# Generated by Django 3.2 on 2023-06-02 23:57

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0009_banners_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAndPreviousEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='events')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('event_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': '18. Current And Previous Events',
            },
        ),
    ]
