# Generated by Django 3.2 on 2023-06-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0011_auto_20230604_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentandpreviousevents',
            options={'verbose_name_plural': '21. Events'},
        ),
        migrations.AlterModelOptions(
            name='mainobjective',
            options={'verbose_name_plural': '09. Objectives'},
        ),
        migrations.AlterField(
            model_name='currentandpreviousevents',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
